### ISSUE TITLE
Working fine but .....

### ISSUE THREAD

**Issue by 404notfound-3** [devanshbatham/ArchiveFuzz#2]
Why it couldn't found my DDNS from noip.com ??

404......... ddns.net
![Screenshot_2020-03-04-10-18-41-86_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/52858429/75865926-46f01d00-5e2a-11ea-92d1-01747760d76a.png)

**Comment by devanshbatham** [comment]
It just checks Webarchives for subdomains, not all subdomains are archived , only archived domains are showing
